class Terran:
	class Structure:
		Barracks			= 'Barracks.jpg'
		Bunker			= 'Bunker.jpg'
		Bunker_update			= 'Bunker_update.jpg'
		Refinery			= 'Refinery.jpg'
		Sensor_tower			= 'Sensor_tower.jpg'
		Stargate			= 'Stargate.jpg'
		Supply_depot			= 'Supply_depot.jpg'
		Ghost_academy			= 'Ghost_academy.jpg'
		Command_center			= 'Command_center.jpg'
		Starport			= 'Starport.jpg'
		Engineering_bay			= 'Engineering_bay.jpg'
		Factory			= 'Factory.jpg'
		Fusion_core			= 'Fusion_core.jpg'
		Missile_turret			= 'Missile_turret.jpg'
		Orbital_command			= 'Orbital_command.jpg'
		Reactor			= 'Reactor.jpg'
		Tech_Lab			= 'Tech_Lab.jpg'

	class Units:
		Battlecruiser			= 'Battlecruiser.jpg'
		Raven			= 'Raven.jpg'
		SCV			= 'SCV.jpg'
		Siege_tank			= 'Siege_tank.jpg'
		Thor			= 'Thor.jpg'
		Viking			= 'Viking.jpg'
		Widow_mine			= 'Widow_mine.jpg'
		Ghost			= 'Ghost.jpg'
		Hellbat			= 'Hellbat.jpg'
		Hellion			= 'Hellion.jpg'
		Cyclone			= 'Cyclone.jpg'
		Banshee			= 'Banshee.jpg'
		Liberator			= 'Liberator.jpg'
		Marauder			= 'Marauder.jpg'
		Marine			= 'Marine.jpg'
		Medivac			= 'Medivac.jpg'
		MULE			= 'MULE.jpg'

	class Upgrade:
		Advanced_Ballistics			= 'Advanced_Ballistics.jpg'
		Armory			= 'Armory.jpg'
		Arm_Silo_with_Nuke			= 'Arm_Silo_with_Nuke.jpg'
		Caduceus_Reactor			= 'Caduceus_Reactor.png'
		Cloak			= 'Cloak.jpg'
		Combat_Shield			= 'Combat_Shield.jpg'
		StimPack			= 'StimPack.jpg'
		Tectonic_Destabilizers			= 'Tectonic_Destabilizers.png'
		Terran_Ship_Weapons			= 'Terran_Ship_Weapons.gif'
		Terran_Vehicle_and_Ship_Plating			= 'Terran_Vehicle_and_Ship_Plating.gif'
		Terran_Vehicle_Weapons			= 'Terran_Vehicle_Weapons.gif'
		Weapon_Refit			= 'Weapon_Refit.jpg'
		Sec_Auto_Tracking			= 'Sec_Auto_Tracking.png'
		Infantry_Armor			= 'Infantry_Armor.gif'
		Infantry_Weapons			= 'Infantry_Weapons.gif'
		Concussive_Shells			= 'Concussive_Shells.jpg'
		Enhanced_Shockwaves			= 'Enhanced_Shockwaves.jpg'
		Neosteel_Armor			= 'Neosteel_Armor.png'

class Protoss:
	class Structure:
		Assimilator			= 'Assimilator.jpg'
		Photon_cannon			= 'Photon_cannon.jpg'
		Pylon			= 'Pylon.jpg'
		Robotics_bay			= 'Robotics_bay.jpg'
		Robotics_facility			= 'Robotics_facility.jpg'
		Shield_battery			= 'Shield_battery.jpg'
		Twilight_council			= 'Twilight_council.jpg'
		Gateway			= 'Gateway.jpg'
		Cybernetics_core			= 'Cybernetics_core.jpg'
		Dark_shrine			= 'Dark_shrine.jpg'
		Forge			= 'Forge.jpg'
		Nexus			= 'Nexus.jpg'

	class Units:
		Adept			= 'Adept.jpg'
		Archon			= 'Archon.jpg'
		Carrier			= 'Carrier.jpg'
		Colossus			= 'Colossus.jpg'
		Phoenix			= 'Phoenix.jpg'
		Probe			= 'Probe.jpg'
		Sentry			= 'Sentry.jpg'
		Stalker			= 'Stalker.jpg'
		Tempest			= 'Tempest.jpg'
		Templar_archives			= 'Templar_archives.jpg'
		Void_ray			= 'Void_ray.jpg'
		Warp_prism			= 'Warp_prism.jpg'
		Zealot			= 'Zealot.jpg'
		Immortal			= 'Immortal.jpg'
		Interceptor			= 'Interceptor.jpg'
		Disruptor			= 'Disruptor.jpg'
		Fleet_beacon			= 'Fleet_beacon.jpg'
		Mothership			= 'Mothership.jpg'
		Observer			= 'Observer.jpg'
		Oracle			= 'Oracle.jpg'

	class Upgrade:
		Anion_Pulse_Crystals			= 'Anion_Pulse_Crystals.png'
		Blink			= 'Blink.png'
		Charge			= 'Charge.jpg'
		Chrono_Boost			= 'Chrono_Boost.jpg'
		Plasma_Shields			= 'Plasma_Shields.gif'
		Protoss_Air_Armor			= 'Protoss_Air_Armor.gif'
		Protoss_Air_Weapons			= 'Protoss_Air_Weapons.gif'
		Resonating_Glaives			= 'Resonating_Glaives.png'
		Shadow_Stride			= 'Shadow_Stride.png'
		Storm			= 'Storm.jpg'
		Warp_Gate_Transformation			= 'Warp_Gate_Transformation.jpg'
		Gravitic_Boosters			= 'Gravitic_Boosters.png'
		Gravitic_Drive			= 'Gravitic_Drive.png'
		Ground_Armor			= 'Ground_Armor.gif'
		Ground_Weapons			= 'Ground_Weapons.gif'
		Extended_Thermal_Lance			= 'Extended_Thermal_Lance.png'
		Feedback			= 'Feedback.jpg'
		Flux_Vanes			= 'Flux_Vanes.png'

class Zerg:
	class Structure:
		Spawning_pool			= 'Spawning_pool.jpg'
		Spine_crawler			= 'Spine_crawler.jpg'
		Spire			= 'Spire.jpg'
		Spore_crawler			= 'Spore_crawler.jpg'
		Swarm_host			= 'Swarm_host.jpg'
		Ultralisk_cavern			= 'Ultralisk_cavern.jpg'
		Greater_spire			= 'Greater_spire.jpg'
		Hatchery			= 'Hatchery.jpg'
		Hydralisk_den			= 'Hydralisk_den.jpg'
		Infestation_pit			= 'Infestation_pit.jpg'
		Lair			= 'Lair.jpg'
		Extractor			= 'Extractor.jpg'
		Nydus_network			= 'Nydus_network.jpg'
		Nydus_worm			= 'Nydus_worm.jpg'

	class Units:
		Baneling			= 'Baneling.jpg'
		Baneling_nest			= 'Baneling_nest.jpg'
		Broodling			= 'Broodling.jpg'
		Brood_lord			= 'Brood_lord.jpg'
		Overseer			= 'Overseer.jpg'
		Queen			= 'Queen.jpg'
		Ravager			= 'Ravager.jpg'
		Roach			= 'Roach.jpg'
		Ultralisk			= 'Ultralisk.jpg'
		Viper			= 'Viper.jpg'
		Zergling			= 'Zergling.jpg'
		High_templar			= 'High_templar.jpg'
		Hive			= 'Hive.jpg'
		Hydralisk			= 'Hydralisk.jpg'
		Infestor			= 'Infestor.jpg'
		Larva			= 'Larva.jpg'
		Overlord			= 'Overlord.jpg'
		Corruptor			= 'Corruptor.jpg'
		Creep_tumor			= 'Creep_tumor.jpg'
		Drone			= 'Drone.jpg'
		Locust			= 'Locust.jpg'
		Mutalisk			= 'Mutalisk.jpg'

	class Upgrade:
            pass

